
## 不可以重复

功能测试

```python
def test_duplicate_items_cannot_be_added(browser, live_server):
    # 他打开主页, 开启了一个计划
    text = '我的计划'
    browser.get(live_server.url)
    input_box_input_and_enter(text, browser)

    # 不小心输入了重复的内容
    input_box_input_and_enter(text, browser)

    # 她看到了报错
    assert '不能重复输入' in browser.find_element_by_css_selector('.invalid-feedback').text
```

开始干活, 第一步就是写单元测试:

model_test.py:
```python
    def test_duplicate_items_for_the_same_list_should_be_invalid(self):
        list_ = List.objects.create()
        text = 'duplicate'
        Item.objects.create(list=list_, text=text)
        with pytest.raises(IntegrityError):
            Item.objects.create(list=list_, text=text)

    def test_duplicate_items_for_different_lists_should_be_valid(self):
        list1 = List.objects.create()
        list2 = List.objects.create()
        text = 'duplicate'
        Item.objects.create(list=list1, text=text)
        Item.objects.create(list=list2, text=text)
        # assert no raise errors
```

测试肯定失败, 不会有任何错误抛出的. 我们还没写对应代码

model如果这么写的话, 还是失败
```python
class Item(models.Model):
    text = models.TextField(default='', unique=True)
    list = models.ForeignKey('List', default=None, on_delete=models.CASCADE)
```

这次又得用 Meta 了, models.py:

```python
class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey('List', default=None, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['list', 'text']
```

测试通过

### 顺序
接着确保数据输出的顺序没错

```python
def test_objects_dot_all_metohd_order_right(self):
    list_ = List.objects.create()
    item1 = Item.objects.create(list=list_, text='1')
    item2 = Item.objects.create(list=list_, text='2')
    item3 = Item.objects.create(list=list_, text='3')
    
    assert Item.objects.all() == [item1, item2, item3]
```

发现两边没办法比较, 报错:

```bash
<QuerySet [<Item: Item object (1)>, <Item: Item object (2)>, <Item: Item object (3)>]>
```

这个需要我们将对象更好的描述

测试保证:

```python
    def test_objects_dot_all_metohd_order_right(self):
        list_ = List.objects.create()
        item1 = Item.objects.create(list=list_, text='1')
        item2 = Item.objects.create(list=list_, text='2')
        item3 = Item.objects.create(list=list_, text='3')
        
        assert list(Item.objects.all()) == [item1, item2, item3]

    def test_Item_string_representation_should_be_its_text(self):
        item = Item(text='hi')
        assert str(item) == 'hi'
```

model.py:

```python
class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey('List', default=None, on_delete=models.CASCADE)

    def __str__(self):
        ordering = ('id', )
        return self.text

    class Meta:
        unique_together = ['list', 'text']
```

测试通过

运行下面命令, 人工测试会发现变化

```bash
python manage.py makemigrations 
python manage.py migrate  
```

### view 处理重复

功能测试:

```bash
E       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".invalid"}
...
django.db.utils.IntegrityError: UNIQUE constraint failed: lists_item.list_id, lists_item.text
```

而且可以发现浏览器是 500

我们需要在 view 层做一些处理

单元测试, view_test.py

```python
    def test_duplicate_item_input_should_raise_error(self, client):
        list_ = List.objects.create()
        item = Item.objects.create(list=list_, text='hi')

        response = client.post(reverse('items', kwargs={'id': list_.id}), 
                            data={'text': 'hi'})

        assertContains(response, DUPLICATE_ITEM_ERROR)
        # pytest.fail(response.content.decode())
        # assert response.context['form'].errors['text'][0] == DUPLICATE_ITEM_ERROR
        assertTemplateUsed(response, 'lists/list.html', )
        assert Item.objects.all().count() == 
```

这个测试会报错:
```bash
E       sqlite3.IntegrityError: UNIQUE constraint failed: lists_item.list_id, lists_item.text
```

我们想要防止出现这个错误. 我们需要在保存到数据库之前使用 `is_valid` 方法, 从而通知用户有问题. 这之前, 表单需要先知道当前用的是哪一个 list.

### 表单处理重复

我们已经有的表单只需要知道 item 的文本即可. 但是要验证唯一性还需要知道 list 是谁. 就像我们重写 `save` 一样, 这次要构造方法了.

测试保证, forms_test.py:

```python
class TestUniqueItemForm:
    def test_form_item_input_has_placeholder_and_css_classes(self):
        list_ = List.objects.create()
        form = UniqueItemForm(for_list=list_)
        assert 'placeholder="想干点啥?"' in form.as_p()
        assert 'class="form-control input-lg"' in form.as_p()

    def test_empty_item_input_should_raise_error(self):
        list_ = List.objects.create()
        form = UniqueItemForm(for_list=list_, data={'text': ''})
        assert form.is_valid() == False
        assert form.errors['text'] == [EMPTY_ITEM_ERROR]

    def test_duplicate_items_submit_should_raise_error(self):
        list_ = List.objects.create()
        text = 'duplicate'
        Item.objects.create(list=list_, text=text)
        form = UniqueItemForm(for_list=list_, data={'text': text})

        assert form.is_valid() == False
        assert form.errors['text'][0] == DUPLICATE_ITEM_ERROR
```

现在的测试失败, 修改 forms.py:

```python
class UniqueItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)
```

这段代码中, 使用 form 层的 `validate_unique` 调用 数据库层的 `validate_unique`. 如果有错误, 修改错误信息.

测试, 失败:

```bash
lists/tests/view_test.py:66: 
...
django.db.utils.IntegrityError: UNIQUE constraint failed: lists_item.list_id, lists_item.text
```
view_test.py 报错, 因为我们还没有在这里用新的 form


### 使用 UniqueItemForm

view_test.py:

```python
def test_item_list_view_should_use_form(self, client):
    list_ = List.objects.create()
    response = client.get(reverse('items', kwargs={'id': list_.id})) 

    assert isinstance(response.context['form'], UniqueItemForm)
    assertContains(response, 'name="text"')
```

再次测试, 还是失败, 为了探索原因, 修改这个测试:


```python
    def test_duplicate_item_input_should_raise_error(self, client):
        list_ = List.objects.create()
        item = Item.objects.create(list=list_, text='hi')

        response = client.post(reverse('items', kwargs={'id': list_.id}), 
                            data={'text': 'hi'})

        # assertContains(response, DUPLICATE_ITEM_ERROR)
        assert response.context['form'].errors['text'][0] == DUPLICATE_ITEM_ERROR  # 🍄
        pytest.fail(response.content.decode())  # 🐼
        assertTemplateUsed(response, 'lists/list.html', )
        assert Item.objects.all().count() == 1
```

可以发现, 错误为:

```bash
 assert response.context['form'].errors['text'][0] == DUPLICATE_ITEM_ERROR
>       pytest.fail(response.content.decode())
E       Failed: <!DOCTYPE html>
```

这个说明 🍄 没有问题. 那为什么 assertContains 不通过呢? 这个方法会查看相应内容的输出, 如果没有就报错. 查看输出, 的确没有发现此错误提示:

```html
E                           <input type="hidden" name="csrfmiddlewaretoken" value="V6QkGbLeajTVzwhKzJDwAMQIAj1sgRd8b0g4Erj1Tt1BzAfggx7fqseLEcYrq9Eo">
E                           
E                           <input type="text" name="text" value="hi" placeholder="想干点啥?" class="form-control input-lg" id="new_item" required>
E                           <div class="invalid-feedback">
E                               输入框不能为空
E                           </div>
E                       </form>
E                   </div>
```

但是为什么 🍄 没有问题呢? 这是因为表单的确返回了错误, 但是我们没有将其显示出来. 现在修改 base.html:

```html
    ...
    {{ form.text }}
    {% if form.errors %}
        <div class="invalid-feedback">{{ form.text.errors }}</div>
    {% endif %}
</form>
```

这里干脆就先取消了前端验证. 不过最好不要取消前端验证, 这里可以用 js 检测用户输入, 如果输入不合法, 无法提交即可. 这里主要都是 js 的内容, 这里就不展开了.












